---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pzttsfca/card-game.rejoan.com/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH